Feat/gh pages deployment
pyansys/pyfluent-visualization pull request #188
Opened 2023-01-17 16:53 UTC by alikasim72

Updated the conf.py and workflow files to push the built documentation to the gh-pages branch and enable the multi-version feature. 

Afterwards, will require configuring the CNAME outside of GitHub to deploy and host the docs.

2023-01-19 06:26 UTC, jorgepiloto requested changes

2023-01-19 06:26 UTC, jorgepiloto commented on .github/workflows/nightly-doc-build.yml
> +        uses: pyansys/actions/doc-deploy-stable@v2
You can use the latest actions:

```suggestion
        uses: pyansys/actions/doc-deploy-stable@v3
```

2023-01-19 15:55 UTC, alikasim72 commented
@jorgepiloto the suggested changes have been made and the documentation has been migrated to the gh-branch repo. Only the CNAME setup is remaining.

2023-01-19 16:12 UTC, mkundu1 commented on .github/workflows/nightly-doc-build.yml
> +        uses: pyansys/actions/doc-deploy-stable@v3
```suggestion
        uses: pyansys/actions/doc-deploy-dev@v3
```

2023-01-19 16:16 UTC, mkundu1 approved these changes

2023-01-20 13:30 UTC, jorgepiloto approved these changes

2023-01-20 15:34 UTC, merged