Overall edit of PyFluent-Visualization doc
pyansys/pyfluent-visualization pull request #92
Opened 2022-07-28 17:08 UTC by PipKat

This PR has general edits for the PyFluent-Visualization doc. Note, however, that [issue #86](https://github.com/pyansys/pyfluent-visualization/issues/86) must be handled before I thorough review can really be performed. A lot of the existing content is this guide is not specific to PyFluent-Visualization but rather Py-Fluent core.

2022-07-28 18:37 UTC, PipKat commented
@jorgepiloto @RobPasMue Can you look at the log for the failed Documentation check. I can't figure out what the error means, let alone fix it!

2022-07-28 19:13 UTC, jorgepiloto commented on doc/source/api/visualization/matplot_windows_manager.rst
> +    #Plot XY plot on window-1.
A white space needs to be left between the comment sign and the comment itself:

```suggestion
    # Plot XY plot on window-1.
```

2022-07-28 19:13 UTC, jorgepiloto commented on doc/source/api/visualization/matplot_windows_manager.rst
> +    #Plot XY plot on window-1.
I will implement a linter for this via blacken-docs tool.

2022-07-28 19:16 UTC, jorgepiloto requested changes
This may be the reason of the failure, @PipKat.

2022-07-28 19:16 UTC, jorgepiloto commented on doc/source/users_guide/postprocessing.rst
> +~~~~~~~~~~~~~~~
```suggestion
Generate XY plot
~~~~~~~~~~~~~~~~
```

2022-07-28 20:22 UTC, jorgepiloto commented
@PipKat, the documentation is failing because these warnings:

```text
/home/ansys/actions-runner/_work/pyfluent-visualization/pyfluent-visualization/doc/source/index.rst:65: WARNING: undefined label: api reference
/home/ansys/actions-runner/_work/pyfluent-visualization/pyfluent-visualization/doc/source/index.rst:65: WARNING: undefined label: examples
```

which are caused by these lines in the `doc/source/index.rst` file

```text
In addition to installation and usage information, the PyFluent-Visualization
documentation provides :ref:`API reference`, :ref:`Examples`, and :ref:`Contributing`
sections.
```

2022-07-28 20:44 UTC, jorgepiloto commented
I fixed the issues in https://github.com/pyansys/pyfluent-visualization/pull/92/commits/5ba507929f6ea217ab832e987ffed67a6c97ca0b and https://github.com/pyansys/pyfluent-visualization/pull/92/commits/782e53c5dec64180434a5d184708ce25e4de3e17, @PipKat.

The "autosectionlabel" extension needed to be enabled and there was a missing ">" at the end of a link. It took me a bit to spot this last error...

2022-07-28 21:26 UTC, PipKat commented
Thanks so much for figuring out these problems. Words are hard--but code is nearly impossible!

2022-07-29 05:42 UTC, RobPasMue commented
Thanks for looking into this @jorgepiloto!

2022-07-29 07:04 UTC, ajain-work commented on doc/source/users_guide/postprocessing.rst
> +This example demonstrates how you can display the contour object:
```suggestion
This example shows how you can display the contour object:
```

2022-07-29 07:08 UTC, ajain-work commented on examples/00-postprocessing/post_processing_exhaust_manifold.py
> +# Start plot object
```suggestion
# Create plot object
```

2022-07-29 07:08 UTC, ajain-work commented on examples/00-postprocessing/post_processing_exhaust_manifold.py
> +# Start the plot object for the session.
```suggestion
# Create the plot object for the session.
```

2022-07-29 07:10 UTC, ajain-work commented on examples/00-postprocessing/post_processing_exhaust_manifold.py
> +# Plot XY plot
Generate?

2022-07-29 07:16 UTC, RobPasMue commented on examples/00-postprocessing/post_processing_exhaust_manifold.py
> +# Plot XY plot
Agreed

2022-07-29 07:16 UTC, RobPasMue commented on examples/00-postprocessing/post_processing_exhaust_manifold.py
> +# Plot XY plot
```suggestion
# Generate XY plot
```

2022-07-29 08:42 UTC, jorgepiloto requested changes

2022-07-29 08:42 UTC, jorgepiloto commented on examples/00-postprocessing/post_processing_exhaust_manifold.py
> +# ~~~~~~~~~~~~
```suggestion
# Generate XY plot
# ~~~~~~~~~~~~~~~~
```

2022-07-29 08:42 UTC, jorgepiloto commented on examples/00-postprocessing/post_processing_exhaust_manifold.py
> +# ~~~~~~~~~~~~~~~~~
```suggestion
# Create plot object
# ~~~~~~~~~~~~~~~~~~
```

2022-07-29 12:21 UTC, RobPasMue approved these changes

2022-07-29 13:15 UTC, dnwillia-work approved these changes

2022-07-29 13:20 UTC, jorgepiloto approved these changes

2022-07-29 13:32 UTC, merged